name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "✅ Your tests would run here"
           - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
             username: $
             {{ secrets.DOCKER_USERNAME }}
             password: $
             {{ secrets.DOCKER_PASSWORD }}

                   - name: Build Docker image
                     run: |
                       docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .

                - name: Push Docker image
                  run: |
                    docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
